### ISSUE TITLE
Addition of multiple right click events

### ISSUE THREAD

**Issue by svolosd** [TomSchimansky/TkinterMapView#10]
Hi Tom,

Great map control, really enjoying exploring the functionality it has.

When adding multiple events using the tkintermapview.add_right_click_menu_command() method, the user is correctly presented with a list of labelled of options on right click. However, the command invoked is always the command added last (i.e. the bottom most one) and not the command for the selected item. 
I'm assuming the intention was to allow for multiple options on right-click?

David

**Comment by TomSchimansky** [comment]
Hi, thanks for reporting this, it was indeed a bug I didn't noticed yet. But now it's fixed with version 1.9.

**Comment by svolosd** [comment]
Hi Tom,

Tested and working fine as at version 1.9. Thanks for the very prompt turnaround - very much appreciated!

David
