### ISSUE TITLE
Lagging when working with significant number of Polygons

### ISSUE THREAD

**Issue by alexiusacademia** [TomSchimansky/TkinterMapView#100]
I tried this library and it works perfectly for showing map tiles and polygons. It's easy to use as well, thank to the author! However, I am trying to use this in a personal project but when I loaded the polygons, roughly 5,000 polygons, I lags for 2-3 seconds when panning and zooming on the map. I tried to subclass it to applying threading on `draw()` method of a polygon but still no luck and still slow. I wonder if we have any workaround for this? Thank you very much!

**Comment by TomSchimansky** [comment]
There is no workaround, tkinter is just very slow, you have to use an other library or render in the browser with javascript if you want better performance.

**Comment by alexiusacademia** [comment]
Okay thank you very much... I appreciate it and the library is very easy to use...
