### ISSUE TITLE
How to animate map movement

### ISSUE THREAD

**Issue by Kdebaas** [TomSchimansky/TkinterMapView#12]
Hi, thanks for Tkintermapview.

Here is a support question, I hope you have the time to point me in the right direction.

I am trying to create an app where the user can choose two points on a map, and then let the app create an animated panning movement between the two points. I am using my own local tileserver, which are basically tiles of high resolution scans from antique maps. They aren't georeferenced, so it's just basically pixel coordinates.

I'm struggling with getting the map to move. I had hoped the `self.map_widget.draw_move()` call would do it, but it doesn't seem to.

**Comment by Kdebaas** [comment]
Hi, I realize now this question is a little out of the scope of tkintermapview: I'm not used to tkinter GUI programming, and have since yesterday learned about the event loop and how to insert function calls into it. The map moves.

Now I am just struggling with the conversion between pixels, decimals and tilenames.

Cheers

**Comment by Kdebaas** [comment]
So, to summarize:

Solved how to animate the map by looking carefully at ``fading_move()``.

Solved most of my troubles with the conversion between pixels, decimals and tilenames with the utility functions ``decimal_to_osm()`` and ``osm_to_decimal``.

Thanks for your program! I really like the multi-threaded caching of the tiles!

Cheers

**Comment by TomSchimansky** [comment]
Ok, all right if you got it to work. Maybe I will add a `.animate()` function later, to fade between two positions on the map in a specific time.
