### ISSUE TITLE
Adding Functionality to draw polygons - Polygon dissapears when zoomin in and out. 

### ISSUE THREAD

**Issue by rogeralmengor** [TomSchimansky/TkinterMapView#13]
Hi Tom. I am very happy to see such a well developed tool as this one. I think it would be very useful for a project I am developing. My goal for now is to make something similar to the web tool geojson.io (https://geojson.io)
I need to be able to not only draw markers and path, but also to be able to draw a polygon and export it in a geopackage. I have made a couple of trials around your code. As far as I understand the TkinterMapView object is based on Tkinter.Canvas and on top of it you can draw markers and lines between points (I have seen that for this there are utilities that allow to transform OSM basemap coordinates to canvas coordinates). 
I took this idea to modify the code in such a way: 
```python
   def set_marker(self, deg_x: float, deg_y: float, text: str = None, **kwargs) -> CanvasPositionMarker:
        marker = CanvasPositionMarker(self, (deg_x, deg_y), text=text, **kwargs)
        marker.draw()
        self.canvas_marker_list.append(marker)
        return marker

    def create_polygon(self, position_list: list) -> CanvasPolygon:
        polygon = CanvasPolygon(self, position_list)
        polygon.draw() 
        return polygon

    def set_path(self, position_list: list, **kwargs) -> CanvasPath:
        path = CanvasPath(self, position_list, **kwargs)
        path.draw()
        self.canvas_path_list.append(path)
        return path`
```

the create_polygon function I put it between the methods set_marker and set_path of the TkinterMapView class, and as you can see a polygon for this class is created by calling the draw method of this new class I created called CanvasPolygon (I stored it as a new python file called canvas_polygon.py). 
I simply copied everything from CanvasPath class from the canvas_path.py file, and tried to figure out how to make it draw me a polygon, passing the stored coordinates (naturally I have restrictions to be able to make polygon based on at least 3 points (markers)).
When I draw on the canvas, it does so, however, when I zoom out or zoom in, this polygon is lost, it appears and disappears continuously. This does not happen with the CanvasPaths and CanvasPositionMarkers, and I wonder if it has to do with being able to add features that allow me to resize the polygon automatically when the zoom changes. 

I would be very grateful if you could help me with this issue. Below is the code for the CanvasPolygon Builder. Thank you very much for your excellent work.

Roger 
```python
import tkinter
import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .map_widget import TkinterMapView

from .coordinate_convert_functions import deg2num, num2deg


class CanvasPolygon:
    def __init__(self, map_widget: "TkinterMapView", position_list, color="#3E69CB", command=None, name=None):
        self.map_widget = map_widget
        self.position_list = position_list
        self.canvas_polygon_positions = []
        self.connection_list = []
        self.deleted = False

        self.path_color = color
        self.command = command
        self.canvas_line = None
        self.name = name

        self.last_upper_left_tile_pos = None
        self.last_position_list_length = len(self.position_list)

    #def __del__(self):
    #    self.map_widget.canvas.delete(self.canvas_line)
    #    self.canvas_line = None

    #def delete(self):
    #    self.__del__()

    def appear(self):
        self.deleted = False
        self.draw()

    #def add_position(self, deg_x, deg_y, index=-1):
    #    if index == -1:
    #        self.position_list.append((deg_x, deg_y))
    #    else:
    #        self.position_list.insert(index, (deg_x, deg_y))
        # self.draw()

    #def remove_position(self, deg_x, deg_y):
    #    self.position_list.remove((deg_x, deg_y))
    #    self.draw()

    def get_canvas_pos(self, position, widget_tile_width, widget_tile_height):
        tile_position = deg2num(*position, round(self.map_widget.zoom))

        canvas_pos_x = ((tile_position[0] - self.map_widget.upper_left_tile_pos[0]) / widget_tile_width) * self.map_widget.width
        canvas_pos_y = ((tile_position[1] - self.map_widget.upper_left_tile_pos[1]) / widget_tile_height) * self.map_widget.height

        return canvas_pos_x, canvas_pos_y

    #def mouse_enter(self, event=None):
    #    if sys.platform == "darwin":
    #        self.map_widget.canvas.config(cursor="pointinghand")
    #    elif sys.platform.startswith("win"):
    #        self.map_widget.canvas.config(cursor="hand2")
    #    else:
    #        self.map_widget.canvas.config(cursor="hand2")  # not tested what it looks like on Linux!

    #def mouse_leave(self, event=None):
    #    self.map_widget.canvas.config(cursor="arrow")

    #def click(self, event=None):
    #    if self.command is not None:
    #        self.command(self)

    def draw(self, move=False):
        self.last_position_list_length = len(self.position_list)

        widget_tile_width = self.map_widget.lower_right_tile_pos[0] - self.map_widget.upper_left_tile_pos[0]
        widget_tile_height = self.map_widget.lower_right_tile_pos[1] - self.map_widget.upper_left_tile_pos[1]

        if move is True and self.last_upper_left_tile_pos is not None: #and new_line_length is False:
            x_move = ((self.last_upper_left_tile_pos[0] - self.map_widget.upper_left_tile_pos[0]) / widget_tile_width) * self.map_widget.width
            y_move = ((self.last_upper_left_tile_pos[1] - self.map_widget.upper_left_tile_pos[1]) / widget_tile_height) * self.map_widget.height

            for i in range(0, len(self.position_list)* 2, 2):
                self.canvas_polygon_positions[i] += x_move
                self.canvas_polygon_positions[i + 1] += y_move
        else:
            self.canvas_polygon_positions = []
        for position in self.position_list:
            canvas_positions = self.get_canvas_pos(position, widget_tile_width, widget_tile_height)
            #canvas_positions = [item for t in canvas_positions for item in t]
            self.canvas_polygon_positions.append(canvas_positions)
            #self.canvas_line_positions.append(canvas_position[0])
            #self.canvas_line_positions.append(canvas_position[1])

        if not self.deleted:
            if self.canvas_line is None:
                self.map_widget.canvas.delete(self.canvas_line)
                self.canvas_polygon = self.map_widget.canvas.create_polygon(self.canvas_polygon_positions)
                                                                      #width=9, fill=self.path_color,
                                                                      #capstyle=tkinter.ROUND, joinstyle=tkinter.ROUND,
                                                                      #tag="path")

                if self.command is not None:
                    self.map_widget.canvas.tag_bind(self.canvas_line, "<Enter>", self.mouse_enter)
                    self.map_widget.canvas.tag_bind(self.canvas_line, "<Leave>", self.mouse_leave)
                    self.map_widget.canvas.tag_bind(self.canvas_line, "<Button-1>", self.click)
            else:
                self.map_widget.canvas.coords(self.canvas_line, self.canvas_line_positions)
        else:
            self.map_widget.canvas.delete(self.canvas_line)
            self.canvas_line = None

        self.map_widget.manage_z_order()
        self.last_upper_left_tile_pos = self.map_widget.upper_left_tile_pos
```

**Comment by TomSchimansky** [comment]
Hi, I'm glad you like it. I think the reason your'e Polygon disappears is because new tiles get placed above it. My method to manage this is, that I give every element a tkinter canvas `tag`, for example all path elements get `tag="path"`. And when ever something changed on the canvas, for example if you zoom, or move, I call the function `.manage_z_order()` in `map_widget.py line 329`:
```python
    def manage_z_order(self):
        self.canvas.lift("path")
        self.canvas.lift("marker")
        self.canvas.lift("marker_image")
        self.canvas.lift("corner")
        self.canvas.lift("button")
```
By doing this, I make sure the z-order of the elements is always right, and I because this is an inbuilt function of tkinter I think this is somehow efficient 😅, because theoretically I don't need to `.lift()` all elements in every step, because not every z-position will be wrong. But there is no method to give canvas object a z-position if you place them, all you can do is `.lift()` or `.lower()` and if you place them, they will always be on top.

And the reason the size doesn't get updated when zooming is, that the `draw` method of the Polygon is called only once at the beginning and not every time a zoom event happens. For the marker and and the path I created a list inside the map widget, where all markers/path get appended, and so I can draw them every time the canvas gets updated:
```python
        for marker in self.canvas_marker_list:
            marker.draw()

        for path in self.canvas_path_list:
            path.draw()
```
`(map_widget.py line 570)`

So you can try to add a tag to your polygon canvas parts, add them to `manage_z_order` and create a list to update them inside the map_widgets `draw` function, but I think I will also add 
Polygons by myself in the next days...

**Comment by rogeralmengor** [comment]
Hi @TomSchimansky , amazing and detailed answer. I'll try all the suggestions regarding the drawing of polygons. It'll be amazing if the drawing of polygons functionality would be added in the future. Meanwhile I'll do it by myself, modifying the map_viewer file and adding a CanvasPolygon with the corrections you recommended. Thank you very much!

**Comment by TomSchimansky** [comment]
I added polygons now with version 3.10, have a look at https://github.com/TomSchimansky/TkinterMapView#create-polygon-from-position-list. Sadly it's not possible to set an opacity for a polygon on the canvas, that would be cool, but now you can either fill it with a color or make it fully transparent.

**Comment by rogeralmengor** [comment]
Hi Tom, I just tested the functionality to create polygons and it works really well. Thank you very much!
