### ISSUE TITLE
Polygons with donut holes

### ISSUE THREAD

**Issue by DevonTe22** [TomSchimansky/TkinterMapView#16]
Hi Tom, 
I'm trying to display a "donut" polygon that has an outer ring and an inner ring. The way the polygon is with a None type point separating the outer ring points from the inner ring. Something like this (Note, these are just example points from a more complex polygon): 
[ (35.966916026000035, -119.73706605599995), 
(35.963160585000026, -119.73713219299998), 
(35.96310003800005, -119.75422644199995),
(35.96358683400007, -119.75421395799998), 
(35.963579872000025, -119.75467458899999),
(35.96310092900006, -119.75467313499996),
(35.96313411600005, -119.77193926999996),
(35.96316571400007, -119.78990182199999), 
(35.963125637000076, -119.79867769199996),
(35.96308466200003, -119.80750611499997), 
(35.96311094600003, -119.82515756999999),
None, 
(36.04973748100008, -119.80665732999995),
(36.04978930400006, -119.80665667099998), 
(36.049910225000076, -119.80665513499997),
(36.05006180300006, -119.82450578099997) ]

I've been racking my brain on how to display it in your widget (very awesome btw), but  can't think of a better method that this one: https://stackoverflow.com/questions/50071801/erase-area-within-polygon-in-tkinter-canvas. This would work for the most part, but I thought I ask if you had any ideas?

**Comment by TomSchimansky** [comment]
Hi, I don't think you can achieve this with a single polygon, you could create a polygon without a fill color and a very thick border. But to get a polygon with a border and a hole, the only solution would be to use 3 polygons:

<img width="765" alt="Bildschirmfoto 2022-05-04 um 22 56 21" src="https://user-images.githubusercontent.com/66446067/166824643-4ab56e2b-daad-4e5c-bef2-52370cb44aa4.png">

Number 1 and 3 are just line polygons without a fill and number 2 is a polygon without an outline and just a fill color and a hole.
