### ISSUE TITLE
Customizable icon for position marker

### ISSUE THREAD

**Issue by yucai2005** [TomSchimansky/TkinterMapView#17]
Hi Tom,

The current icon for position marker looks good. However, sometimes it can be crowded when there are a lot of position markers in a small area. Would it be better if the icons for position markers are customizable? For example, dots, circles, crosses, stars, or squares with adjustable size, line width, line colour, filling colour, etc.

And thank you for your great work on this package!

Kind Regards

**Comment by TomSchimansky** [comment]
That's a good idea, I will try to implement different shapes in the next time.

**Comment by ucnanoman** [comment]
I'll be working on unit icons such as tank, airplane, airport, infantry unit, etc. 
If and when I complete this, i'll send an update

**Comment by ucnanoman** [comment]
> Hi Tom,
> 
> The current icon for position marker looks good. However, sometimes it can be crowded when there are a lot of position markers in a small area. Would it be better if the icons for position markers are customizable? For example, dots, circles, crosses, stars, or squares with adjustable size, line width, line colour, filling colour, etc.
> 
> And thank you for your great work on this package!
> 
> Kind Regards

In the meantime, you can shrink the current icons and that should help massively, just look into the code there is sizing in there.

**Comment by sarankhaliq2326** [comment]
@TomSchimansky Have you got any progress on this. I am really close at my project but i really need customized markers bro. If you have got any solution please let me know

**Comment by TomSchimansky** [comment]
I added an icon attribute now with version 1.16, where you can pass a PhotoImage object, which will replace the standard location marker:
https://github.com/TomSchimansky/TkinterMapView#create-position-markers

Here is an example program:
https://github.com/TomSchimansky/TkinterMapView/blob/main/examples/map_view_marker_icon_images.py
