### ISSUE TITLE
cannot import coordinate_convert_functions since version 1.10

### ISSUE THREAD

**Issue by Kromilan** [TomSchimansky/TkinterMapView#19]
As written in the title, since version 1.10 (released on April 24 2022) of this module, "from tkintermapview import coordinate_convert_functions" results in:

Import Error: cannot import name 'coordinate_convert_functions' from 'tkintermapview' (XXX/.local/pathon3.10/site-packages/tkintermapview/__init__.py)

This behaviour is not present in 1.9

I used the num2deg function of the coordinate_convert_functions to determine the coordinates of the position on the map, which I clicked on. 
```
x_ratio = event.x/map_widget.winfo_width()
y_ratio = event.y/map_widget.winfo_height()

click_pos = math.num2deg(map_widget.upper_left_tile_pos[0] + (map_widget.lower_right_tile_pos[0] - map_widget.upper_left_tile_pos[0]) * x_ratio,
              map_widget.upper_left_tile_pos[1] + (map_widget.lower_right_tile_pos[1] - map_widget.upper_left_tile_pos[1]) * y_ratio,
              round(map_widget.zoom))
```

have the coordinate_convert_functions been renamed and if so, what is their new name? alternatively, what is currently the best way to retrieve the coordinates of a location on the map, that I clicked on?

**Comment by TomSchimansky** [comment]
The following functions are currently available like this:
```python
from tkintermapview import convert_coordinates_to_address, convert_coordinates_to_country, convert_coordinates_to_city
from tkintermapview import convert_address_to_coordinates
from tkintermapview import decimal_to_osm, osm_to_decimal  # previously deg2num, num2deg
```
