### ISSUE TITLE
Question: delete a marker?

### ISSUE THREAD

**Issue by Tom1954** [TomSchimansky/TkinterMapView#23]
When a marker is activated by pressing the mouse, what name will it get? Can this name be used directly to to delete the marker by "marker".delete?

**Comment by ucnanoman** [comment]
Instead just create your own marker function and then you'll know what the name of the marker is to delete.
Seems like the dev here created all the functionality for you to go off and use the modules and go nuts.
Example of what i've done with this, I add and delete markers and display airports for a simulation.
![image](https://user-images.githubusercontent.com/61528637/175863194-1a9c7e5f-2bf6-44a1-b5b8-8d03f920c920.png)
