### ISSUE TITLE
Offline Map Example in Readme

### ISSUE THREAD

**Issue by rbumga** [TomSchimansky/TkinterMapView#26]
The link on the github page to the 'using offline map tiles' example is pointing to the wrong link. It exists in the folder and I looked there instead, just thought you should know.

edit: it's this one https://github.com/TomSchimansky/TkinterMapView/blob/main/examples/map_with%20offline_tiles.py

**Comment by TomSchimansky** [comment]
Thanks

**Comment by rbumga** [comment]
@TomSchimansky Cool! Do you have happen to have any recommendations on optimizing performance with an offline tile database? I'm running this on a raspberry pi 3 and don't have too much processing power to spare with other processes running.

**Comment by TomSchimansky** [comment]
Do you mean the download performance or the performance while rendering the tiles form the database? The download is indeed very slow, but I don't really know how to speed it up, because im using multithreading already.

**Comment by jgoyao** [comment]
The link is not properly set: https://github.com/TomSchimansky/TkinterMapView/blob/main/examples/map_with_offline_tiles.py

**Comment by TomSchimansky** [comment]
fixed

**Comment by rbumga** [comment]
I’m talking about reading from the database, sorry I wasn’t clear. It seems
pretty quick now reading a tile set I downloaded, just wondering if you had
any suggestions if I had a large number of other processes running
simultaneously.
