### ISSUE TITLE
Path line color and line width options

### ISSUE THREAD

**Issue by sylvanoMTL** [TomSchimansky/TkinterMapView#27]
I am looking at changing the line thickness and colors of GPS path, but I cannot see the option. 
Ideally I would like to change the line color with other metrics (e.g. speed, altitude...) , using rainbow or parula chart

Is there any methods to control these line options?

**Comment by TomSchimansky** [comment]
You can change the color of a path by passing a `color`attribute to .set_path(). Changing the width is currently not supported, but maybe I will implement this in the future.

**Comment by staceellis** [comment]
I'd also love to see a width argument for set_path. I see you can change the width of a drawn line in canvas_path.draw.

**Comment by sylvanoMTL** [comment]
here are the modifications to bring to [canvas_path.py](https://github.com/TomSchimansky/TkinterMapView/blob/main/tkintermapview/canvas_path.py) to change the line width:

class object constructuor: add a self.path_width:

```
class CanvasPath:
    def __init__(self,
                 map_widget: "TkinterMapView",
                 position_list,
                 color="#3E69CB",
                 width=9,
                 command=None,
                 name=None,
                 data: any = None):

        self.map_widget = map_widget
        self.position_list = position_list
        self.canvas_line_positions = []
        self.deleted = False

        self.path_color = color
        self.path_width = width
        self.command = command
        self.canvas_line = None
        self.name = name
        self.data = data

```


set_path function line 101: change:  ` width=9 `  to `width=self.width`

**Comment by TomSchimansky** [comment]
I added width attribute now with version 1.17. color attribute was added a while ago.
