### ISSUE TITLE
Load KML into Map as a line/point

### ISSUE THREAD

**Issue by Davidb8** [TomSchimansky/TkinterMapView#30]
I am wanting to preview KML files in a larger python script, as to not separately use google earth. Is there a way to load in a KML file (specifically a line and several points) into the map, and make it viewed? My KMLs are 3d, but are okay to be viewed in 2d.

**Comment by TomSchimansky** [comment]
You would have to parse the KML file yourself and add markers and path accordingly. I don't think I will add a KML parser, would be way too much work.
