### ISSUE TITLE
Possible usage policy violation

### ISSUE THREAD

**Issue by Y-o-p** [TomSchimansky/TkinterMapView#33]
I've been using your library for about a week without any issues, and it's been working as intended. But without making any changes to my code, today the map stopped displaying tiles. I've tried messing with environments and even used one of your examples, but it's still just a grey image. Upon further debugging, it seems like it fails in the request and returns a 403 restricted in this line of code.
```Python
image = Image.open(requests.get(url, stream=True).raw)
```
But if I add a User-Agent header it works again. Not sure exactly what's going on, but there is this section on their [Tile Usage Policy](https://operations.osmfoundation.org/policies/tiles/#:~:text=Valid%20HTTP%20User%2DAgent%20identifying%20application.%20Faking%20another%20app%E2%80%99s%20User%2DAgent%20WILL%20get%20you%20blocked.%20Using%20a%20library%E2%80%99s%20default%20User%2DAgent%20is%20NOT%20recommended.). Here are some resources on their help site: [1](https://help.openstreetmap.org/questions/24740/why-am-i-all-of-a-sudden-getting-error-403/24755), [2](https://help.openstreetmap.org/questions/72225/http-error-403-forbidden-accessing-tile/72243). It may be the case that you have to specify a custom User-Agent to adhere to their technical usage requirements since it's not being requested from a browser.

**Comment by dty717** [comment]
Add a header in request in map_widget.py.


            headers = {
                "Host": "a.tile.openstreetmap.org",
                "Connection": "keep-alive",
                "Pragma": "no-cache",
                "Cache-Control": "no-cache",
                "sec-ch-ua": "\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"",
                "sec-ch-ua-mobile": "?0",
                "sec-ch-ua-platform": "\"Windows\"",
                "Upgrade-Insecure-Requests": "1",
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                "Sec-Fetch-Site": "none",
                "Sec-Fetch-Mode": "navigate",
                "Sec-Fetch-User": "?1",
                "Sec-Fetch-Dest": "document",
                "Accept-Encoding": "gzip, deflate, br",
                "Accept-Language": "en,en-US;q=0.9,zh;q=0.8,zh-CN;q=0.7,de;q=0.6"
            }
            url = self.tile_server.replace("{x}", str(x)).replace("{y}", str(y)).replace("{z}", str(zoom))
            image = Image.open(requests.get(url, stream=True,headers = headers).raw)

            if self.overlay_tile_server is not None:
                url = self.overlay_tile_server.replace("{x}", str(x)).replace("{y}", str(y)).replace("{z}", str(zoom))
                image_overlay = Image.open(requests.get(url, stream=True,headers = headers).raw)

**Comment by Y-o-p** [comment]
> Add a header in request in map_widget.py.
> 
> ```
>         headers = {
>             "Host": "a.tile.openstreetmap.org",
>             "Connection": "keep-alive",
>             "Pragma": "no-cache",
>             "Cache-Control": "no-cache",
>             "sec-ch-ua": "\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"",
>             "sec-ch-ua-mobile": "?0",
>             "sec-ch-ua-platform": "\"Windows\"",
>             "Upgrade-Insecure-Requests": "1",
>             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
>             "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
>             "Sec-Fetch-Site": "none",
>             "Sec-Fetch-Mode": "navigate",
>             "Sec-Fetch-User": "?1",
>             "Sec-Fetch-Dest": "document",
>             "Accept-Encoding": "gzip, deflate, br",
>             "Accept-Language": "en,en-US;q=0.9,zh;q=0.8,zh-CN;q=0.7,de;q=0.6"
>         }
>         url = self.tile_server.replace("{x}", str(x)).replace("{y}", str(y)).replace("{z}", str(zoom))
>         image = Image.open(requests.get(url, stream=True,headers = headers).raw)
> 
>         if self.overlay_tile_server is not None:
>             url = self.overlay_tile_server.replace("{x}", str(x)).replace("{y}", str(y)).replace("{z}", str(zoom))
>             image_overlay = Image.open(requests.get(url, stream=True,headers = headers).raw)
> ```

You shouldn't be sending no-cache headers according to their usage requirements. Also, they say not to fake another app's User-Agent. So, I don't think you should impersonate Chrome. But, it's not entirely clear whether you can or can't do that.

The reason we should specify a User-Agent is because requests sends its own, which is not recommended. It may be best to make a custom one such as `{"User-Agent": "TkinterMapView/1.12"}`. [Here is another post](https://help.openstreetmap.org/questions/66990/my-applications-access-to-nominatimopenstreetmaporg-is-blocked-forbidden/66996) that also points to that. I think the reasoning is that they want to know who is using their free service in order to limit malicious requests.

**Comment by dty717** [comment]
That's not a problem, @Y-o-p. As HTTP has a common feature that "On the Internet, nobody knows you're a dog", it's very hard to be detected as a fake User-Agent.

**Comment by TomSchimansky** [comment]
I added a user agent (`{"User-Agent": "TkinterMapView"}`) now, and the OpenStreetMap server should work fine now.
