### ISSUE TITLE
Facing Error while using the module

### ISSUE THREAD

**Issue by VISHWAAR** [TomSchimansky/TkinterMapView#34]
Whenever, the map widget is called using the tkintermapview.TkinterMapView(), the result is just a box with the zoom in an out buttons. I was able to see the map, two days before, but I am unable to see it now. As I said earlier, just a box is only visible. Hope this would be resolved as soon as possible. Thank you
![Screenshot (24)](https://user-images.githubusercontent.com/88718524/178561902-15db4084-64a6-4e73-acd4-4ff6b666898c.png)
![Screenshot (25)](https://user-images.githubusercontent.com/88718524/178561909-12ea090c-64d3-47a3-bb3b-a3c46579c7f4.png)

**Comment by Y-o-p** [comment]
Probably related to this issue: https://github.com/TomSchimansky/TkinterMapView/issues/33#issue-1301138806

**Comment by VISHWAAR** [comment]
Is there any other way, through which I can use to bring in the maps in my tkinter window?. Please do suggest any other methods so that I can complete my project. Thank you.

**Comment by TomSchimansky** [comment]
If its a usage restriction problem, just try an other tile server.

**Comment by VISHWAAR** [comment]
Thank you for the reply sir. I am just a beginner, so could you tell me how to do it sir.

**Comment by TomSchimansky** [comment]
I added a User-Agent now with version 1.13 so it should work now, just upgrade to the new version.
