### ISSUE TITLE
Having troubles using a variable in creating a marker

### ISSUE THREAD

**Issue by LukeyBookey21** [TomSchimansky/TkinterMapView#39]
It’ll allow me to manually put the co ordinates in but will not allow me to put a variable containing the exact same co ordinates in the same format. Would anyone have a solution to this thanks.

**Comment by TomSchimansky** [comment]
Can you post your code?

**Comment by LukeyBookey21** [comment]
def pins():
       global translation
       global rdata
       conn = sqlite3.connect('address_book.db')
       c = conn.cursor()
       c.execute("SELECT * FROM parking")
       data1 = c.fetchone()
       rdata = (data1[0])
       print(rdata)
       marker_1 = map_widget.set_marker(rdata, text="52.55, 13.4")
       
       conn.commit()
    
       conn.close()


>>>53.727830, -1.353003

not sure what to do as when I paste that co ordinate manually it works fine, but when I put in rdata it seems to be having none of it. New to Tkinter so Im probs missing something silly, help would be appreciated. cheers

**Comment by TomSchimansky** [comment]
`set_marker` method needs the position as two different attributes.
```python
 marker_1 = map_widget.set_marker(rdata[0], data[1], text="52.55, 13.4")

# or

 marker_1 = map_widget.set_marker(*rdata, text="52.55, 13.4")  # split the tuple into arguments with * operator
```
