### ISSUE TITLE
Offline Map

### ISSUE THREAD

**Issue by jgoyao** [TomSchimansky/TkinterMapView#42]
The offline map: https://github.com/TomSchimansky/TkinterMapView/blob/main/examples/map_with_offline_tiles.py
Is not showing the content downloaded and stored in the db file.

I have used the [load_offline_tiles.py](https://github.com/TomSchimansky/TkinterMapView/blob/main/examples/load_offline_tiles.py) to generate the nyc database and afterwards the  [map_with_offline_tiles.py] (https://github.com/TomSchimansky/TkinterMapView/ blob/main/examples/map_with_offline_tiles.py)

The window showed is blank and nothing is displayed. If I change the property of the "use_database_only" to False, everythin is loaded except to nyc, which means that the database is not properly created with the script or the widget is not properly getting the information from the database.

Answer: It a matter of the osm tile policies, this means the tiles requested by the downloader do not have the tile.

Thanks in advance

**Comment by TomSchimansky** [comment]
Does it work now? I added a user-agent to the request method like I did for the map_widget a while ago?
