### ISSUE TITLE
Show image instead of marker

### ISSUE THREAD

**Issue by vargaaronR** [TomSchimansky/TkinterMapView#47]
Hello,

is it possible to show only the image and hide the orange/red marker at map_view_marker_example? So show the choosen image instead of the marker.
Thanks your answer in advance!

BR,
Aron

**Comment by TomSchimansky** [comment]
Hi, currently there is no built in option for this. Maybe I will add this, but currently I#m working on other projects. But if I have the time I will go through all of the issues on this project and see if I can implement the enhancements.

**Comment by TomSchimansky** [comment]
I added an icon attribute now with version 1.16, where you can pass a PhotoImage object, which will replace the standard location marker:
https://github.com/TomSchimansky/TkinterMapView#create-position-markers

Here is an example program:
https://github.com/TomSchimansky/TkinterMapView/blob/main/examples/map_view_marker_icon_images.py

**Comment by KFischbach18** [comment]
Tom,

Using your tkintermapview, i'm not able to use this "icon" parameter. I have version 1.29 installed, what is the paramter name for this???
