### ISSUE TITLE
Smoother Zoom

### ISSUE THREAD

**Issue by kXborg** [TomSchimansky/TkinterMapView#53]
At the moment, the zoom step size is 1. Is it possible to set it to something like 0.1 to make a smooth zoom effect?

**Comment by TomSchimansky** [comment]
It would be possible if tkinter would support image resizing on the canvas. But it does not. So its not possible because I would have to resize the tile images with PIL into a lot of different resolutions for a smooth zoom to the next zoom step. But PIL is way too slow for this.
