### ISSUE TITLE
Click on map to get city name

### ISSUE THREAD

**Issue by mkserg84** [TomSchimansky/TkinterMapView#8]
Hello,

Firstly, let me thank you for sharing the module.
I would like to know is there any way to click on the map and get Lat/Lon or City Name from it in pop-up window so I can manipulate this info for my needs.
Thanks in advance.

**Comment by TomSchimansky** [comment]
Hey, so at the moment, you only can do `map_widget.get_position()` and get the current decimal position which is at the center of the map_widget. But I can implement a mouse click callback for the whole map, where you get the clicked position. Then you can place a new marker on the clicked position with a label.
I will try to do it in the next days.

**Comment by mkserg84** [comment]
Thank you very much. I will be appreciated (y)

**Comment by mkserg84** [comment]
Hi mate,
Do you have any ETR for the feature?

**Comment by TomSchimansky** [comment]
Hi, I added a right click menu now, where you can add commands by yourself, which will get the current coords as a tuple argument. Is this what you had in mind? You can find it in the readme with a small example here: https://github.com/TomSchimansky/TkinterMapView#right-click-menu-on-map

**Comment by mkserg84** [comment]
Thanks for the update.
Unfortunately, it is not something I need.
What I need is to Left click on the map and get in the background variable the Lon/Lat of the place I clicked and then I could manipulate the information further.
Can you please Left-click with the return variable of the Lat/Lon?
Thanks in advance.

**Comment by TomSchimansky** [comment]
Ok, but you have to keep in mind that there is a left click every time you drag the map, but I can do it...

**Comment by mkserg84** [comment]
Is there any way to keep the hand on the left click and just click on the map to be distinguished?

**Comment by TomSchimansky** [comment]
A solution would be, to only trigger the coordinates event, when the user clicks without any movement. But then the event wouldn't be triggered  until you release the left mouse button and not when you click it. Because you have to wait till the button is released, to now if there wasn't any movement after the click down. But that would be possible.

**Comment by mkserg84** [comment]
Dear Tom,
Since I am new to programming I didn't get your last comment. However, I got this error when trying to copy coordinates to the clipboard poorly clicking on the right-click coordinates as per your instruction "where you can view the current decimal coordinates and copy them into the clipboard by clicking them".
Can you please help to tackle this issue? 
Will be much appreciated. Thanks in advnace.
![Screenshot at 2022-04-10 22-53-08](https://user-images.githubusercontent.com/51739090/162637397-e867bd48-cd83-400f-99e2-523d1abb1699.png)

**Comment by mkserg84** [comment]
Just make you clear on my task.
I need to click on the map and once clicked it should open another small window showing the current city's weather. So in this case it is not fit my needs since I should right-click on the map do something else and then create some small windows for the weather info. Thanks in advance.

**Comment by TomSchimansky** [comment]
Ok this is a bug, I use https://pypi.org/project/pyperclip/ for the clipboard copying and as it says on the website you may need qt4 on Linux, I will try to find another way to copy to the clipboard on Linux..

**Comment by TomSchimansky** [comment]
Does the clipboard copying now work for you if you do an upgrade?

**Comment by mkserg84** [comment]
No, the same error comes out.

**Comment by TomSchimansky** [comment]
Ok, then you possibly need to install xclip: `sudo apt-get install xclip`
There is no way of copying to the clipboard on Linux just with system tools, I think.

**Comment by mkserg84** [comment]
Thanks, mate, I install it and the error disappeared now, 
Can you please give me an example of how to manipulate the clipboard so during the runtime of the program I can click on the map and save the coordinates in the clipboard and then use it to find the city name with these coordinates?

**Comment by mkserg84** [comment]
Also every time I click on coords it pops up this message which is not needed.
![image](https://user-images.githubusercontent.com/51739090/163238832-0f6079d4-6af8-470f-b2f0-d0f086bc156f.png)

**Comment by TomSchimansky** [comment]
The message is intended, so that the user nows that the coordinates were copied, otherwise you wouldn't now anything happened if you don't know of this feature, maybe I will make it a small message on the widget itself instead of a tkinter.message.

I uploaded version 1.7 now and as you can see in the documentation I added a method to add a left click callback function which gets the clicked decimal coordinates as a tuple argument:
```python
def left_click_event(coordinates_tuple):
    print("Left click event with coordinates:", coordinates_tuple)
    
map_widget.add_left_click_map_command(left_click_event)
```

I also added some utility functions to the library so that you can convert the decimal coords to am address or city name:
```python
city = tkintermapview.convert_coordinates_to_city(51.5122057, -0.0994014)
# city: "City of London"
```
```python
adr = tkintermapview.convert_coordinates_to_address(51.5122057, -0.0994014)
print(adr.street, adr.housenumber, adr.postal, adr.city, adr.state, adr.country, adr.latlng)
# Output: Knightrider Street None EC4 City of London England United Kingdom [51.512284050000005, -0.09981746110011651]
```

**Comment by mkserg84** [comment]
Hi mate,
Thanks for the function.
Please tell me how can I use the tuple it creates out of function. 

def left_click_event(coordinates_tuple):
    print("Left click event with coordinates:", coordinates_tuple)
    
map_widget.add_left_click_map_command(left_click_event)

Let's say, I need coordinates to put inside the below function that I got from the above function. 
city = tkintermapview.convert_coordinates_to_city(51.5122057, -0.0994014)
How can I do that ?
Thanks in advance.

**Comment by TomSchimansky** [comment]
If you have a tuple you can get the individual values with indexes or you split the tuple into two variables:
```python
tkintermapview.convert_coordinates_to_city(coordinates_tuple[0], coordinates_tuple[1])

value_x, value_y = coordinates_tuple
tkintermapview.convert_coordinates_to_city(value_x, value_y)
```
But that's a very basic question, and you should just read a tutorial on how python tuples work. There are thousands of good python tutorials out there teaching you the fundamentals of python.  I will not answer this kind of questions here in the future, if they are unrelated to TkinterMapView.

**Comment by mkserg84** [comment]
I found it already mate. Thanks. Sorry for bothering you.

**Comment by mkserg84** [comment]
My friend the tile you used returns names of the cities or countries with local names. Is there any way to change that parameter and get English names instead?

**Comment by TomSchimansky** [comment]
I use the `geocoder` library to convert the coordinates to a city. You can have a look if you get english names with some other method: https://geocoder.readthedocs.io/index.html

I use the OSM server in reverse mode: `adr = geocoder.osm([45.15, -75.14], method='reverse')`
But there are other servers available, just try them out: https://geocoder.readthedocs.io/api.html#reverse-geocoding

**Comment by mkserg84** [comment]
Thank you mate for your time and consideration. Appreciated it.
