### ISSUE TITLE
Export to gpx or kml

### ISSUE THREAD

**Issue by SurafelTesfaye** [TomSchimansky/TkinterMapView#81]
Hello, after drawing a waypoint on the map with button click event, how can one export it to a gpx or kml format?

**Comment by gfm71** [comment]
You can use modules gpxpy and simplekml to do this. It's pretty easy:
https://github.com/tkrajina/gpxpy/blob/dev/examples/waypoints_example.py
https://simplekml.readthedocs.io/en/latest/gettingstarted.html#quick-example
