### ISSUE TITLE
Location based movement 

### ISSUE THREAD

**Issue by SurafelTesfaye** [TomSchimansky/TkinterMapView#88]
Hi I am using tkintermapview for my project, so far everything went very well. I was using Matlab mapping toolbox but I found this quite handy. My issue is, I am able to read gpx coordinates (latitude and longitude) from other script. I want to draw those lines over the map like say I have a delivery guy moving in real-ime and seeing his location over this tkintermapview. It could be a dot or square or something moving over the map in real time.

**Comment by kaledawit** [comment]
Dear have you got a solution? Same problems.

**Comment by SurafelAnshebo** [comment]
Hey Kal no - I would say change your approach. I dont know what you are doing but I switched to Flask and Leaflet and works like charm
