### ISSUE TITLE
Question: Displaying  optimum route from source to destination

### ISSUE THREAD

**Issue by ShankarGanapathy** [TomSchimansky/TkinterMapView#92]
By any chance is there any function that's created already to show the shortest path via the map displayed form Source to Destination or do I have to find out another way to implement that on top of this code ?

It could be done by taking multiple points along the path from source to destination and then plotting/ drawing a line between all those points.

**Comment by TomSchimansky** [comment]
Finding the shortest path on a map is a huge topic in its own and you would have to use an other library or probably an online service for that.
